license_id: cc-by-igo
methodology: Registry
caveats: None
dataset_source: CERF
package_creator: HDX Data Systems Team
private: False
maintainer: ccc6d05d-d2fd-45f9-be24-05c340968b4b
owner_org: cerf
data_update_frequency: 7
subnational: 0
